version: "3.8"

services:
  node:
    build: .
    container_name: car_shop
    working_dir: /app
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: car_shop_frontend
    ports:
      - 5173:5173
    depends_on:
      - node
    restart: always

  mongodb:
    image: mongo:4.4.17-rc0
    container_name: car_shop_db
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: car_shop_net
